server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:usuariosdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
